# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='Article Title')),
                ('enable_comment', models.BooleanField(default=True, verbose_name='Enable Comment')),
                ('plubished', models.BooleanField(default=True, verbose_name='Is Plublish')),
                ('file_used', models.BooleanField(default=True, verbose_name='Is file used')),
                ('content', models.TextField(blank=True)),
                ('content_file', models.FileField(blank=True, upload_to=b'articles/', verbose_name='Content File')),
            ],
            options={
                'ordering': ['-create_time'],
                'abstract': False,
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(max_length=1024, verbose_name='Category Description')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(max_length=100, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tag Name')),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='Article Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag', verbose_name='Article Tags'),
        ),
    ]
