# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='plubished',
        ),
        migrations.AddField(
            model_name='article',
            name='pubished',
            field=models.BooleanField(default=True, verbose_name='Is Publish'),
        ),
    ]
