# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-14 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_change_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='bg_color',
            field=models.CharField(default=b'blue-grey', max_length=50, verbose_name='Bg color name'),
        ),
        migrations.AddField(
            model_name='tag',
            name='text_color',
            field=models.CharField(default=b'white-text', max_length=50, verbose_name='text color name'),
        ),
    ]
